version: 0.2

phases:
  build:
    commands:
      - echo "Build stage - HTML"
  post_build:
    commands:
      - echo "Uploading file to S3 bucket..."
      - aws s3 cp index.html s3://training-1-devops/

artifacts:
  files:
    - index.html
